Avro - toJson should work exactly as toBinary
twitter/bijection pull request #256
Opened 2016-09-20 20:30 UTC by mariussoutier

Adapt `toJson` to work similarly as `toBinary` in order to support generated Scala case classes as specific records.

2016-09-23 22:00 UTC, johnynek commented on bijection-avro/src/main/scala/com/twitter/bijection/avro/AvroCodecs.scala
> +  def toJson[T <: SpecificRecordBase: ClassTag]: Injection[T, String] = {
can we add a new method name and not break binary compatibility?

2016-09-23 22:00 UTC, johnynek requested changes

2016-09-24 10:18 UTC, mariussoutier commented on bijection-avro/src/main/scala/com/twitter/bijection/avro/AvroCodecs.scala
> +  def toJson[T <: SpecificRecordBase: ClassTag]: Injection[T, String] = {
Sure, it's what I suggested when we changed `toBinary`, but you guys decided it was unnecessary. I'll update the PR.

2016-09-24 16:37 UTC, johnynek commented
We since added a binary compatibility check to CI and changed the process
for publishing when that check fails. Sorry for the hassle.
On Sat, Sep 24, 2016 at 03:19 Marius Soutier <notifications@github.com>
wrote:

> *@mariussoutier* commented on this pull request.
> ------------------------------
>
> In
> bijection-avro/src/main/scala/com/twitter/bijection/avro/AvroCodecs.scala
> <https://github.com/twitter/bijection/pull/256>:
>
> > @@ -121,10 +121,11 @@ object SpecificAvroCodecs {
>      * @tparam T compiled Avro record
>      * @return Injection
>      */
> -  def toJson[T <: SpecificRecordBase: ClassTag](schema: Schema): Injection[T, String] = {
> -    val klass = classTag[T].runtimeClass.asInstanceOf[Class[T]]
> -    val writer = new SpecificDatumWriter[T](klass)
> -    val reader = new SpecificDatumReader[T](klass)
> +  def toJson[T <: SpecificRecordBase: ClassTag]: Injection[T, String] = {
>
> Sure, it's what I suggested when we changed toBinary, but you guys
> decided it was unnecessary. I'll update the PR.
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/twitter/bijection/pull/256>, or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAEJdtgope7S0Gfqsvpdz3NigV8MSek4ks5qtPkigaJpZM4KCG5w>
> .
>

2016-09-24 16:44 UTC, mariussoutier commented
Is the updated PR not binary compatible?

2016-09-24 16:47 UTC, johnynek commented
Failed the scala format test. Can you run sbt scalafmt and commit the changes?

2016-09-24 17:20 UTC, mariussoutier commented
Done!

2016-09-26 17:46 UTC, johnynek commented on bijection-avro/src/main/scala/com/twitter/bijection/avro/AvroCodecs.scala
>    def toJson[T <: SpecificRecordBase: ClassTag](schema: Schema): Injection[T, String] = {
I'd live to remove the `ClassTag` here if possible, but that would be a binary incompatible break, so we can leave it as a TODO for now.

2016-09-26 17:47 UTC, johnynek commented on bijection-avro/src/main/scala/com/twitter/bijection/avro/AvroCodecs.scala
> +  def toBinary[T <: SpecificRecordBase: ClassTag](schema: Schema): Injection[T, Array[Byte]] = {
does this actually use the `ClassTag`? I don't see where. If not, since we already dropped it in a previous version, why not correct that issue?

2016-09-26 17:48 UTC, johnynek requested changes
If we can, let's remove the `ClassTag` on the `toBinary`. If I'm missing something, let's add a comment and leave it.

Thanks for updating the PR!

2016-09-26 19:18 UTC, mariussoutier commented on bijection-avro/src/main/scala/com/twitter/bijection/avro/AvroCodecs.scala
> +  def toBinary[T <: SpecificRecordBase: ClassTag](schema: Schema): Injection[T, Array[Byte]] = {
Good point, done!

2016-09-26 19:18 UTC, mariussoutier commented on bijection-avro/src/main/scala/com/twitter/bijection/avro/AvroCodecs.scala
>    def toJson[T <: SpecificRecordBase: ClassTag](schema: Schema): Injection[T, String] = {
Ok I added a todo.

2016-09-26 19:25 UTC, johnynek approved these changes
Thanks!

2016-09-27 16:19 UTC, mariussoutier commented
All checks successful, merge away ;)

2016-09-27 19:26 UTC, merged

2016-09-27 19:26 UTC, johnynek commented
Thank you!